"""Initial Meta-compliant models

Revision ID: d17af55e7e4c
Revises: 
Create Date: 2026-08-10 14:38:18.136843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17af55e7e4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_id'), 'factories', ['id'], unique=False)
    op.create_index(op.f('ix_factories_phone_number'), 'factories', ['phone_number'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('availability', sa.Enum('IN_STOCK', 'OUT_OF_STOCK', name='availability'), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('primary_media_url', sa.String(length=500), nullable=False),
    sa.Column('additional_media_urls', sa.JSON(), nullable=True),
    sa.Column('meta_product_id', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='syncstatus'), nullable=True),
    sa.Column('sync_error_message', sa.Text(), nullable=True),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_product_id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_factories_phone_number'), table_name='factories')
    op.drop_index(op.f('ix_factories_id'), table_name='factories')
    op.drop_table('factories')
    # ### end Alembic commands ###
